spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sns
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4  # ??? ?? ?? ?? ?? (??? ?? ?? ??)
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      format_sql: true  # SQL ?? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL ????? ??
    show-sql: true  # SQL ??? ??? ????? ??

